[theme]
primaryColor = "#4285f4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#202124"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false
